name: Deploy GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  repository_dispatch:
    types:
      # for dispatch from contentful via webhook
      - deploy
#  schedule:
#    - cron: '*/5 * * * *'

concurrency:
  # to disable multiple parallel jobs during changes in contentful
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  NUXT_ROUTER_BASE_URL: '/maja-wedding-web/'
  FULL_BASE_URL: 'https://SonyPony.github.io/maja-wedding-web/'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Render website
        run: yarn generate

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
#          cname: na.brnodobry.cz
